// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgCxCMOuKf1XcaN-cseWQxo_m9ihGuTJI',
    appId: '1:6765200208:web:7673b59f29782342352255',
    messagingSenderId: '6765200208',
    projectId: 'no2-g8',
    authDomain: 'no2-g8.firebaseapp.com',
    storageBucket: 'no2-g8.firebasestorage.app',
    measurementId: 'G-D8NYNNT4NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLsn0NsgLbIr2S0E5CbclboTZnJ9AWHA',
    appId: '1:6765200208:android:04a66d62158f05cd352255',
    messagingSenderId: '6765200208',
    projectId: 'no2-g8',
    storageBucket: 'no2-g8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHlnvnHqQ2V3RHIhyEUYudeksesdd39M',
    appId: '1:6765200208:ios:d744a1bb37ccbc4b352255',
    messagingSenderId: '6765200208',
    projectId: 'no2-g8',
    storageBucket: 'no2-g8.firebasestorage.app',
    iosBundleId: 'com.example.zemiMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHlnvnHqQ2V3RHIhyEUYudeksesdd39M',
    appId: '1:6765200208:ios:d744a1bb37ccbc4b352255',
    messagingSenderId: '6765200208',
    projectId: 'no2-g8',
    storageBucket: 'no2-g8.firebasestorage.app',
    iosBundleId: 'com.example.zemiMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgCxCMOuKf1XcaN-cseWQxo_m9ihGuTJI',
    appId: '1:6765200208:web:bde30bd743e61890352255',
    messagingSenderId: '6765200208',
    projectId: 'no2-g8',
    authDomain: 'no2-g8.firebaseapp.com',
    storageBucket: 'no2-g8.firebasestorage.app',
    measurementId: 'G-BD8DVZLXVV',
  );
}
